### ISSUE TITLE
UI: Filters on project page

### ISSUE THREAD

**Issue by Aelerinya-old** [ImpactMarkets/impact-markets-app#49]
# Todo
- [x] Types of projects are cut
- [x] The second filter is cut when multiple types are selected in the first filter
- [x] Change color of placeholders from gray to a color which looks less "disabled"

![image](https://user-images.githubusercontent.com/13947008/213015744-8f6e69a4-df60-4cc2-affd-b7915e744117.png)
