### ISSUE TITLE
UI: Logout & profile page

### ISSUE THREAD

**Issue by Aelerinya-old** [ImpactMarkets/impact-markets-app#52]
# Todo

- [ ] Align the edit and sign out buttons to the left, so the sign out button is not cut.
- [x] Redirect to home page after logout
- [ ] [Long user names get cut](https://app.impactmarkets.io/profile/cl5si3edc6061xuop62p4imof)

![image](https://user-images.githubusercontent.com/13947008/213017987-4a636bd4-a9a3-4b34-837f-9a97b40f7c08.png)
